config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  get 'home/about' => 'homes#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  
  validates :body, presence: true
  validates :title, presence: true
  validates :body, length: {maximum:200}
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :_comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
  end
  def after_sign_out_path_for(resource)
     root_path
  end
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    book_comment = BookComment.find(params[:id])
    book_comment.destroy
    redirect_to book_path(params[:book_id])
  end
  
  private
  def book_comment_params
    params.require(:book_comment).permit(:comment, :user_id, :book_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user
    @favorite = Favorite.new
  end
  
  def show
    @book = current_user.books.build
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @favorite = Favorite.new
    @book_comment = BookComment.new
  end
  
  def new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :"index"
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render 'edit'
      flash[:danger]= "Book"
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
    def book_params
      params.require(:book).permit(:title, :body)
    end
  
    def correct_user
      @book = Book.find(params[:id])
      if current_user != @book.user
        redirect_to books_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash[:notice] = "Signed out successfully."
  end

  def about
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    flash[:notice] = "Signed out successfully."
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books.all
  end

  def new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def user_params
      params.require(:user).permit(:name, :profile_image, :introduction)
  end
  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1>Editing Book</h1>
        <%= form_with model:@book, local:true do |f| %>
          <% if @book.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@book.errors.count, "error") %>prohibited this book from being saved</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <div class="field row">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title, class:"col-xs-12 book_title" %>
          </div>
          <div class="field row">
            <%= f.label :body, "Opinion" %>
            <%= f.text_area :body, class:"col-xs-12 book_body" %>
          </div>
          <div class="actions row">
            <%= f.submit "Update Book", class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %>
        <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
        <table class='table table striped'>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
        </table>
        <div class="row">
          <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
        </div>
        <h2>New book</h2>
        <%= form_with model:@book, url:books_path, method: :post, local:true do |f| %>
          <% if @book.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@book.errors.count, "error") %>prohibited this book from being saved</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
        <div class="field row">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class:"col-xs-12 book_title" %>
        </div>
        <div class="field row">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class:"col-xs-12 book_body" %>
        </div>
        <div class="actions row">
          <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
        </div>
        <% end %>
      </div>
      <div class="col-xs-9">
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><span><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: '40x40'), user_path(book.user) %></span></td>
              <td><span><%= link_to book.title, book_path(book)%></span></td>
              <td><span><%= book.body %></span></td>
              <td><span>
              <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(book), method: :post do %>
                  <i class="fa fa-heart-o" aria-hidden="true"></i>
                <% end %>
              <% end %>
              <%= book.favorites.count %>
              </span></td>
              <td><span>コメント数：<%= book.book_comments.count %></span></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= notice %>
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
          <table class='table table striped'>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>Introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </table>
          <div class="row">
            <% if @user.id == current_user.id %>
            <%= link_to "",edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
            <% else %>
            <%= link_to "",user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
            <% end %>
          </div>
          <h2>New book</h2>
          <%= form_with model:@book_new, url:books_path, method: :post, local:true do |f| %>
            <% if @book.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h2><%= pluralize(@book.errors.count, "error") %>prohibited this book from being saved</h2>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field row">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title, class:"col-xs-12 book_title" %>
          </div>
          <div class="field row">
            <%= f.label :body, "Opinion" %>
            <%= f.text_area :body, class:"col-xs-12 book_body" %>
          </div>
          <div class="actions row">
            <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %>
      </div>
      <div class="col-xs-9">
        <h2>Book detail</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><span><%= attachment_image_tag @user, :profile_image, :fill, 100, 100,fallback: "no_image.jpg" %><br><%= link_to @user.name, user_path(@book.user.id) %></span></td>
              <td><span><%= link_to @book.title, book_path(@book) %></span></td>
              <td><span><%= @book.body %></span></td>
              <td><span>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@book), method: :delete do %>
                  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <% end %>
              <% else %>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="fa fa-heart-o" aria-hidden="true"></i>
                <% end %>
              <% end %>
              <%= @book.favorites.count %>
              </span></td>
              <% if @user.id == current_user.id %>
              <td><span><%= link_to 'Edit', edit_book_path(@book),class: "btn btn-success"  %></span></td>
              <td><span><%= link_to 'Destroy', book_path(@book), class: "btn btn-danger", method: :delete ,"data-confirm" => "本当にますか?"%></span></td>
              <% end %>
              <td><span>コメント数：<%= @book.book_comments.count %></span></td>
            </tr>
          </tbody>
        </table>
        
        <div class="comment-list bt style-2" id="comments">
          <ol>
            <% @book.book_comments.each do |book_comment| %>
              <ol class="comment">
                <div class="comment-body bb">
                  <div class="comment-avatar">
                    <div class="avatar">
                      <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
                    </div>
                  </div>
                  <div class="comment-text">
                    <div class="comment-author clearfix">
                      <a href="#" class="link-author"><%= book_comment.user.name %></a>
                    </div>
                    <div class="comment-entry"><%= book_comment.comment %></div>
                    <% if book_comment.user == current_user %>
                      <div>
                        <%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </ol>
              <% end %>
            </ol>
        </div>
        
        <div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
          <h3 class="section-title left">
            <span>コメント</span>
          </h3>
        </div>

        <%= form_for [@book, @book_comment] do |f| %>
          <div class="row">
            <div class="col-sm-12">
              <%= f.text_area :comment, rows:'5', class: "form-control" %>
            </div>
          </div>
          <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="body">
  <div class="container">
      <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/index.html.erb
<div class="body">
  <div class="container">
  <p id="notice">Signed out successfully.</p>
	  <div class="row">
      <div class='top-message col-md-offset-3 col-md-6'>
        <h1>welcome to <span class='glyphicon glyphicon-book'><strong>Bookers</strong>  !!</h1>
          <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>
        <div class="btn-wrapper">
          <div class="row">
             <p><%= link_to "Log in", new_user_session_path, class:"btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
          </div>
          <div class="row">
            <p><%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1 sign_up" %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c48f5abc4e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to ' Users', users_path, class: "glyphicon glyphicon-user users" %>
              </li>
              <li>
                <%= link_to 'Books', books_path, class: "glyphicon glyphicon-book books"%>
              </li>
              <li>
                <%= link_to "logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout"%>
              </li>
                <% else %>
              <li>
                <%= link_to "Home", root_path, class: "glyphicon glyphicon-home home"%>
              </li>
              <li>
                <%= link_to "About", home_about_path, class: "glyphicon glyphicon-link about" %>
              </li>
              <li>
                <%= link_to "sign up", new_user_registration_path , class: "glyphicon glyphicon-edit sign_up" %>
              </li>
              <li>
                <%= link_to "login", new_user_session_path , class: "glyphicon glyphicon-log-in sign_in" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
  	    <div class="row">
      	  <div class="col-xs-3 col-xs-offset-9">
      		  <p>CopyRight Infratop.inc</p>
      	  </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="body">
  <div class="container">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <% if @user.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(@user.errors.count, "error") %>prohibited this book from being saved</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="field">
        <label for="user_name">Name</label>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image %>
      </div>
      <div class="field">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction %>
      </div>
      <div class="actions">
        <input type="submit" name="commit" value="Update User" data-disable-with="Update User">
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
         <table class='table table striped'>
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr>
              <th>Introduction</th>
              <th><%= current_user.introduction %></th>
            </tr>
          </table>
        <div class="row">
          <%= link_to "", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
        </div>
        <h2>New book</h2>
        <%= form_with model:@book, url:books_path, method: :post, local:true do |f| %>
          <% if @book.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@book.errors.count, "error") %>prohibited this book from being saved</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
          <div class="field row">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title, class:"col-xs-12 book_title" %>
          </div>
          <div class="field row">
            <%= f.label :body, "Opinion" %>
            <%= f.text_area :body, class:"col-xs-12 book_body" %>
          </div>
          <div class="actions row">
            <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %>
      </div>
      <div class="col-xs-9">
        <h2>Users</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><span><%= attachment_image_tag user, :profile_image, :fill, 40, 60, fallback: "no_image.jpg", size:'40x40' %></span></td>
              <td><span><%= user.name %></span></td>
              <td><span><%= link_to "Show", user_path(user) %></span></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= notice %>
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
         <table class='table table striped'>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>Introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </table>
        <div class="row">
          <% if @user.id == current_user.id %>
          <%= link_to "",edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
          <% else %>
          <%= link_to "",user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
          <% end %>
        </div>
        <h2>New book</h2>
        <%= form_with model:@book, url:books_path, method: :post, local:true do |f| %>
          <% if @book.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <h2><%= pluralize(@book.errors.count, "error") %>prohibited this book from being saved</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
          <div class="field row">
            <%= f.label :title, "Title" %>
            <%= f.text_field :title, class:"col-xs-12 book_title" %>
          </div>
          <div class="field row">
            <%= f.label :body, "Opinion" %>
            <%= f.text_area :body, class:"col-xs-12 book_body" %>
          </div>
          <div class="actions row">
            <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
          </div>
        <% end %>
      </div>
      <div class="col-xs-9">
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><span><%= attachment_image_tag @user, :profile_image, :fill, 40, 40,fallback: "no_image.jpg"%></span></td>
              <td><span><%= link_to book.title, book_path(book)%></span></td>
              <td><span><%= book.body %></span></td>
              <td><span>コメント数：<%= book.book_comments.count %></span></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div  